name: 🛠️ Build GDExtension
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

concurrency:
  group: ci-${{github.actor}}-${{github.head_ref || github.run_number}}-${{github.ref}}-runner
  cancel-in-progress: true

jobs:
  build:
    runs-on: ${{ matrix.runner }}
    name: ${{ matrix.name }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - identifier: windows-debug
            name: 🏁 Windows Debug
            cache-name: windows-debug
            runner: ubuntu-22.04
            target: template_debug
            platform: windows
            arch: x86_64
          - identifier: windows-release
            name: 🏁 Windows Release
            cache-name: windows-release
            runner: ubuntu-22.04
            target: template_release
            platform: windows
            arch: x86_64
          - identifier: linux-debug
            name: 🐧 Linux Debug
            cache-name: linux-debug
            runner: ubuntu-22.04
            target: template_debug
            platform: linux
            arch: x86_64
          - identifier: linux-release
            name: 🐧 Linux Release
            cache-name: linux-release
            runner: ubuntu-22.04
            target: template_release
            platform: linux
            arch: x86_64
          - identifier: macos-debug
            name: 🍎 MacOS (universal) Debug
            cache-name: macos-debug
            runner: macos-latest
            target: template_debug
            platform: macos
            arch: universal
          - identifier: macos-release
            name: 🍎 MacOS (universal) Release
            cache-name: macos-release
            runner: macos-latest
            target: template_release
            platform: macos
            arch: universal
          - identifier: android-debug
            name: 🤖 Android Debug
            cache-name: android-debug
            runner: ubuntu-22.04
            target: template_debug
            platform: android
            arch: arm64
          - identifier: android-release
            name: 🤖 Android Release
            cache-name: android-release
            runner: ubuntu-22.04
            target: template_release
            platform: android
            arch: arm64

    steps:
      - name: (Windows) Install mingw64
        if: ${{ startsWith(matrix.identifier, 'windows-') }}
        shell: sh
        run: |
          sudo apt-get install mingw-w64
          sudo update-alternatives --set x86_64-w64-mingw32-gcc /usr/bin/x86_64-w64-mingw32-gcc-posix
          sudo update-alternatives --set x86_64-w64-mingw32-g++ /usr/bin/x86_64-w64-mingw32-g++-posix

      - name: (Android) Install JDK 17
        if: ${{ startsWith(matrix.identifier, 'android-') }}
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: (Android) Install Android SDK
        if: ${{ startsWith(matrix.identifier, 'android-') }}
        uses: android-actions/setup-android@v3

      - name: (Android) Install NDK r23c
        if: ${{ matrix.platform == 'android' }}
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r23c
          link-to-sdk: true

      - name: Install Python
        uses: actions/setup-python@v2

      - name: Install SCons
        shell: bash
        run: |
          python -c "import sys; print(sys.version)"
          python -m pip install scons
          scons --version

      - name: Checkout project
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Set up SCons cache
        uses: actions/cache@v3
        with:
          path: |
            ${{ github.workspace }}/**/.scons-cache/
            ${{ github.workspace }}/**/.sconsign.dblite
            ${{ github.workspace }}/gdextension/godot-cpp/gen/
          key: ${{ matrix.identifier }}-${{ github.ref }}-${{ github.sha }}
          restore-keys: |
            ${{ matrix.identifier }}-${{ github.ref }}-${{ github.sha }}
            ${{ matrix.identifier }}-${{ github.ref }}-
            ${{ matrix.identifier }}-

      - name: Compile extension
        shell: sh
        env:
          SCONS_CACHE: '${{ github.workspace }}/.scons-cache/'
          SCONS_CACHE_LIMIT: 4096
        run: |
          scons target='${{ matrix.target }}' platform='${{ matrix.platform }}' arch='${{ matrix.arch }}'
        working-directory: gdextension
      
      - name: Move binaries to artifact folder
        shell: sh
        run: |
          mkdir -p '${{ github.workspace }}/artifact/'
          mv '${{ github.workspace }}/project/addons/' '${{ github.workspace }}/artifact/addons/'
      
      - name: Copy extra files to addon folder
        shell: sh
        run: |
          cp '${{ github.workspace }}/README.md' '${{ github.workspace }}/logo.svg' '${{ github.workspace }}/LICENSE' '${{ github.workspace }}/artifact/addons/godui/'

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.identifier }}
          path: '${{ github.workspace }}/artifact'
