name: 🛠️ Build and upload gdextension to github releases
on:
  push:
    paths: ["gdextension/**"]
    branches: ["main"]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.runner }}
    name: ${{ matrix.name }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - identifier: windows-debug
            name: 🏁 Windows Debug
            runner: ubuntu-20.04
            target: template_debug
            platform: windows
            arch: x86_64
          - identifier: windows-release
            name: 🏁 Windows Release
            runner: ubuntu-20.04
            target: template_release
            platform: windows
            arch: x86_64
          - identifier: linux-release
            name: 🐧 Linux Release
            runner: ubuntu-20.04
            target: template_release
            platform: linux
            arch: x86_64
          - identifier: linux-debug
            name: 🐧 Linux Debug
            runner: ubuntu-20.04
            target: template_debug
            platform: linux
            arch: x86_64
          - identifier: macos-debug
            name: 🍎 macOS (universal) Debug
            runner: macos-latest
            target: template_debug
            platform: macos
            arch: universal
          - identifier: macos-release
            name: 🍎 macOS (universal) Release
            runner: macos-latest
            target: template_release
            platform: macos
            arch: universal
          - identifier: android-release
            name: 🤖 Android Release
            runner: ubuntu-20.04
            target: template_release
            platform: android
            arch: arm64

    steps:
      - name: Checkout project
        uses: actions/checkout@v3
        with:
          submodules: recursive
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Set up SCons
        shell: bash
        run: |
          python -c "import sys; print(sys.version)"
          python -m pip install scons
          scons --version
      
      - name: Set up Java 11
        if: ${{ matrix.platform == 'android' }}
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      - name: Set up Android SDK
        if: ${{ matrix.platform == 'android' }}
        uses: android-actions/setup-android@v2
      
      - name: Windows dependencies
        if: ${{ matrix.platform == 'windows' }}
        shell: sh
        run: |
          sudo apt-get install mingw-w64
          sudo update-alternatives --set x86_64-w64-mingw32-gcc /usr/bin/x86_64-w64-mingw32-gcc-posix
          sudo update-alternatives --set x86_64-w64-mingw32-g++ /usr/bin/x86_64-w64-mingw32-g++-posix

      - name: Linux dependencies
        if: ${{ matrix.platform == 'linux' }}
        shell: sh
        run: |
          sudo apt-get update -qq
          sudo apt-get install -qqq build-essential pkg-config
      
      - name: Compile godot-cpp
        shell: sh
        run: |
          scons target='${{ matrix.target }}' platform='${{ matrix.platform }}' arch='${{ matrix.arch }}'
        working-directory: gdextension/godot-cpp

      - name: Compile extension
        shell: sh
        run: |
          scons target='${{ matrix.target }}' platform='${{ matrix.platform }}' arch='${{ matrix.arch }}' -j2
        working-directory: gdextension

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.event.repository.name }}
          path: 'project/addons/'
